<?php

/**
 * @file
 *  Language API for RU.
 */

class SL7ApiLang {

  /**
   * Функция возвращает окончание для множественного числа слова на основании
   * числа и массива окончаний.
   *
   * @param integer $number
   *  Число на основе которого нужно сформировать окончание
   * @param array $endingsArray
   *  Массив слов или окончаний для чисел (1, 4, 5),
   *  например array('яблоко', 'яблока', 'яблок').
   * @return String
   */
  public static function getNumEnding($number, array $endingArray) {
    $number = $number % 100;
    if ($number >= 11 && $number <= 19)
      $ending = $endingArray[2];
    else
    {
      $i = $number % 10;
      switch ($i)
      {
        case 1: $ending = $endingArray[0]; break;
        case 2:
        case 3:
        case 4: $ending = $endingArray[1]; break;
        default: $ending = $endingArray[2];
      }
    }
    return $ending;
  }
}